duccao:
  kafka:
    enable-ssl: false
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        auto.register.schema: false
      compression-type: snappy
      idempotence: true
      max-in-flight-request-per-connection: 1
      retries: 3
      security:
        protocol: PLAINTEXT
    consumer:
      max-poll-records: 100
      enable-auto-commit: false
      isolation-level: read_committed
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        auto.register.schema: false
    schema-registry:
      url: http://localhost:8081
      cache-size: 2000
      properties:
        auto.register.schema: false
    listener:
      ack-mode: manual_immediate
      log-container-config: true
      idle-event-interval: 300000

services:
  kafka:
    topic:
      frontline-assessment-topic: frontline.transaction-assessment-record
    consumer:
      retry:
        interval: 0
        max-attempts: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari: &commonHikariConfig
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: PostgreSQLHikariCP
      validation-timeout: 3000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
